//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Repository
{
    using EF_Repository.Interfaces;
    using System;
    using System.Collections.Generic;

    public partial class Game : IEntity
    {
        public int Id { get; set; }
        public string GameName { get; set; }
        public int YearOfProduction { get; set; }
        public int GenreId { get; set; }
        public int PublisherID { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
